version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build
  deploy-to-render:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_DEPLOY_HOOK_URL

workflows:
  run-tests-and-deploy-to-render:
    jobs:
      - start-server
        # Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render:
          requires:
            - run-component-tests
          filters:
            branches:
              only: main
